### ISSUE TITLE
Chris-Prime FactionsPE plugin

### ISSUE THREAD

**Issue by EndreEndi** [RevivalPMMP/PluginRequests#3]
I need a Chris-Prime's FactionsPE plugin, Chris deleted FactionsPE resposity, i need for a FactionsPE plugin save, of identic plugin with him plugin.
Sorry for my bad English!

**Comment by Sandertv** [comment]
@Chris-Prime didn't delete it, but made it private. He has the reason that faction plugins take SO much work, and he plans on using it on his own server.

**Comment by EndreEndi** [comment]
But i need his plugin......You can give me his plugin?

**Comment by Sandertv** [comment]
No, sorry. Even if I did have the possibilty I wouldn't, as I do respect the decision of him.

**Comment by Kris-Driv** [comment]
Thanks @Sandertv.

Matei, as million times said the answer is just no! Why should I give it out for free. In period of year there is 20% chance that at least one human will say thanks instead of complaining about installation process. Even less chance is to earn money. Is it worthy?

**Comment by EndreEndi** [comment]
:(
