### ISSUE TITLE
Top Voter Reward / Logger

### ISSUE THREAD

**Issue by Leejit** [RevivalPMMP/PluginRequests#5]
# When requesting a plugin, please make sure to:
- [x] Put the title in the issue name.
- [x] Give a link to the github page of the plugin.
- [x] Address any errors/issues you encounter for us to watch out for.

# Thank you!

This isn't a plugin that's been made already, as far as I'm aware.

A little about me to be brief. 
I'm Canadian, Male, 26, Hosting a little server called PureCraftPE

Looking to have a plugin made, either by good nature, or for profit. 

Looking for a plugin that can log a players overall amount of votes, as well as automatically reward a player for having the highest amount of votes in the current month. 

TopVoter by SalmonDE uses the vote sites data to get the top voters, if a plugin could be made similar to log the votes and reward a voter at an amount of votes, or reward them how VoteReward does but at the end of the month for having the most amount of votes. 

this would be useful, and great to have on my server & possibly for other servers if they like the idea. 

Please let me know if this is a possibility you can help me with. 

Thanks
-Josh

**Comment by Magicode1** [comment]
Sounds Really Interesting! We moved our Plugin Requests to our Forums: http://revivalpmmpforums.gq/
