### ISSUE TITLE
Mob spawner sell/buy system like PC factions and AdvancedFaction core

### ISSUE THREAD

**Issue by TheAz928** [RevivalPMMP/PluginRequests#6]
Hey, I was looking for a plugin like PC faction's mobpawner sell/buy..
Sorry haven't got any link and also another plugin request is PocketFactions or AdvancedFactions. Thanks !

**Comment by CortexPE** [comment]
https://sellfy.com/p/cjdZ/

**Comment by TheAz928** [comment]
@CortexPE I cannot buy XD

**Comment by Magicode1** [comment]
Please Request Plugins Here: http://revivalpmmpforums.gq/
