### ISSUE TITLE
REQUEST-AUTOMATICDOOR

### ISSUE THREAD

**Issue by Starflux** [RevivalPMMP/PluginRequests#7]
# When requesting a plugin, please make sure to:
- [x] Put the title in the issue name.
- [x] Give a link to the github page of the plugin.
- [x] Address any errors/issues you encounter for us to watch out for.

# Thank you!
https://github.com/organization/automaticDoor

This is a simple plugin that automatically opens doors, the plugin currently works **only in the default world**.

PHP	7.0.15
PocketMine-MP-1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)

as the developer no longer has time to support this would you be interested in making it Multi World supported with the option to enable/disable within config.yml?

Kind Regards
Star

P.S love the work you are doing and thankyou for the support it is greatly appreciated.

**Comment by hiilikewiki** [comment]
No problem. This would be a good project

**Comment by Starflux** [comment]
archie thanks for taking a look at this.

i have no idea at all about php i am in no way looking to press you for the plugin but i am interested in when you believe it could potentially be brought online.

kind regards 
Star

may the code be with you

**Comment by hiilikewiki** [comment]
@Starflux lol?

**Comment by Starflux** [comment]
You got me I don't understand?

**Comment by hiilikewiki** [comment]
@Starflux Yes
