### ISSUE TITLE
Please make this work with PurePerms <3

### ISSUE THREAD

**Issue by Leejit** [RevivalPMMP/PluginRequests#8]
# When requesting a plugin, please make sure to:
- [x] Put the title in the issue name.
- [x] Give a link to the github page of the plugin.
https://github.com/ecoron/RankUp
- [x] Address any errors/issues you encounter for us to watch out for.

# Thank you!

**Comment by hiilikewiki** [comment]
Sorry, what?

**Comment by Leejit** [comment]
Are you blind or dumb ?

There is a link, click it and download the plugin...set it up, use it, it
doesnt work lile it should.

So... "Please make this work wirh PurePerms" was all the description
needed, and a link... right under where it says add a repo link.


so.... sorry...what?

**Comment by hiilikewiki** [comment]
Please do not be rude about this. I made a small mistake. My apologies

**Comment by LordJoshie** [comment]
Then dont be sarcastic with your "Sorry, what?" 's ...

Just be like "I dont understand, am I missing something about this issue
post for a plugin to be fixed ?"

Cuz yeah, clearly you did.

Glad we sorted that all out. :*

Kisses boo.

Now fix plz cutie.

**Comment by hiilikewiki** [comment]
Please post this on the forums instead.

**Comment by Leejit** [comment]
LOL, THEN WHATS THIS REPO FOR... LMFAO.

**Comment by hiilikewiki** [comment]
Maybe you should read readme
Warning: If you persist being rude you will be banned
